---
- hosts: webservers
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: install webserver on redhat
    yum:
      name: httpd
      state: present

  - name: start the webserver
    service:
      name: httpd
      state: started
  
