---
- hosts: webservers
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: install webserver on redhat
    yum:
      name: httpd
      state: present

  - name: start the webserver
    service:
      name: httpd
      state: started

  - name: copy index file into all nodes
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
      
  - name: restart the webserver 
    service: 
      name: httpd
      state: restarted
  
